name: PSL APP CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  pull_request_target:
    types:
      - closed

jobs:
  rebase-check:
    name: Rebase Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Skip rebase check if not a PR
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "Not a PR event, skipping rebase check."

      - name: Set target branch variable (for PR events)
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "TARGET_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV

      - name: Check if branch is rebased on target branch (for PR events)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch origin $TARGET_BRANCH
          if [ "$(git merge-base HEAD origin/$TARGET_BRANCH)" != "$(git rev-parse origin/$TARGET_BRANCH)" ]; then
            echo "The branch is not rebased on $TARGET_BRANCH."
            exit 1
          fi

  build:
    name: Build Front Application
    runs-on: ubuntu-latest
    needs: [rebase-check]
    if: |
      (github.event_name == 'pull_request' && success()) ||
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')) ||
      (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build

  i18n:
    name: Verify Translations
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Verify translations
        run: |
          node -e "const fs = require('fs');
          const en = JSON.parse(fs.readFileSync('src/core/i18n/langs/en.json', 'utf8'));
          const fr = JSON.parse(fs.readFileSync('src/core/i18n/langs/fr.json', 'utf8'));
          const missingInFr = Object.keys(en).filter(key => !(key in fr));
          const missingInEn = Object.keys(fr).filter(key => !(key in en));
          if (missingInFr.length > 0 || missingInEn.length > 0) {
            console.error('Missing keys detected:');
            if (missingInFr.length > 0) {
              console.error('Keys in en.json but not in fr.json:', missingInFr);
            }
            if (missingInEn.length > 0) {
              console.error('Keys in fr.json but not in en.json:', missingInEn);
            }
            process.exit(1);
          } else {
            console.log('All keys are present in both translation files.');
          }"

  notify_discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request_target'
    needs: [build]
    steps:
      - name: Define message and notify Discord
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          AUTHOR: ${{ github.actor }}
          BRANCH: ${{ github.head_ref || github.ref_name }}
          TARGET_BRANCH: ${{ github.base_ref || github.ref_name }}
          STATUS: ${{ needs.build.result }}
        run: |
          MESSAGE=""
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            if [[ "$STATUS" == "success" ]]; then
              MESSAGE="✅ **La PR de #$BRANCH vers /$TARGET_BRANCH sur le front-end est prête à être mergée pour le front !** 🎉"
            else
              MESSAGE="❌ **La PR de #$BRANCH vers /$TARGET_BRANCH sur le front-end n'est PAS prête à être mergée pour le front.** 🚨"
            fi
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            if [[ "$STATUS" == "success" ]]; then
              MESSAGE="🚀 **Déploiement réussi du front sur /$TARGET_BRANCH par $AUTHOR !** 🎉"
            else
              MESSAGE="❌ **Le déploiement du front sur /$TARGET_BRANCH a échoué car le build a failed.** 🚨"
            fi
          fi

          curl -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
               -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               https://discord.com/api/v9/channels/$DISCORD_CHANNEL_ID/messages
